import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <style>
                {`
          :root {
            --asset-prefix: ${process.env.NEXT_PUBLIC_ASSET_PREFIX};
          }
        `}
            </style>
            <body className={inter.className}>
                {/* <Suspense fallback={<Loading/>}> */}

                <Navbar />
                {children}
                {/* </Suspense> */}
            </body>
        </html>
    );
}
